---
- name: Create rdp.map/ipchecker.lua files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: /etc/haproxy/maps, state: directory, mode: '0755' }
    - { path: /etc/haproxy/maps/rdp.map, state: touch, mode: '0644' }
    - { path: /etc/haproxy/ipchecker.lua, state: touch, mode: '0644' }

- name: HAProxy Broker service
  ansible.builtin.include_role:
    name: "{{ roles.role }}"
  loop_control:
    loop_var: roles
  loop:
    - role: ansible-common-role
    - role: ansible-haproxy-broker-role
